name: Check Base Branch

on:
  workflow_call:
    inputs:
      development-branch-name:
        description: 'The name of the development branch that pull requests should target'
        required: false
        type: string
        default: 'main'
      stable-branch-name:
        description: 'The name of the stable branch'
        required: false
        type: string
        default: 'stable'
      skip-check-label:
        description: 'The label used to skip this check'
        default: 'skip-base-branch-check'
        type: string
        required: false

jobs:
  maybe-set:
    if: github.base_ref == inputs.stable-branch-name
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set the pull request base ref
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls/${{ github.event.number }} \
            -f base='${{ inputs.development-branch-name }}'
  check:
    name: Require Development Branch
    needs: [maybe-set]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Base Ref is Development Branch
        if: ${{ !contains(github.event.*.labels.*.name, inputs.skip-check-label) }}
        run: |
          base_ref=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls/${{ github.event.number }} \
            | jq '.base.ref'
          )
          if [[ "${base_ref}" != ${{ inputs.development-branch-name }} ]]
          then
              echo "::error::Pull Request base ref must be the development branch: '${{ inputs.development-branch-name }}'. Found base ref: '${{ github.base_ref }}' ."
              echo "If you're sure you need to merge this change into '${{ github.base_ref }}' instead. "
              echo "You can add the label '${{ inputs.skip-check-label }}'. "
              exit 1
          fi
